### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by CrazyBebop** [fayaz12g/aar-launcher#2]
Couldn't find you on any discords, so I wanted to say thanks for the awesome tool.

cheers.

**Comment by CrazyBebop** [comment]
Oh, I wanted to ask if you could add https://gamebanana.com/games/20511 and all the mods that are recommended for Echos of Wisdom to AAR? Thank you!

**Comment by fayaz12g** [comment]
@CrazyBebop Currently writing a reddit post and gamebanana page for it :) Echoes of Wisdom looks sick with AAR and a new algorithm I wrote. Thanks for the kind words! If you have reddit, check out r/AnyAspectRatio, it's where I post updates most often.

**Comment by fayaz12g** [comment]
Update: The post is done and can be found below
Reddit: https://www.reddit.com/r/AnyAspectRatio/comments/1fu3t4y/echoes_of_wisdom_aar_released/
GameBanana: https://gamebanana.com/mods/545899

More visual fixes/stability mods might be added in the future
